# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_digits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitview',
            name='word',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ассоциация'),
        ),
    ]
